### ISSUE TITLE
 Error PEFT is not installed and No naistyles.csv found

### ISSUE THREAD

**Issue by Myuniqous** [EnragedAntelope/ComfyUI-Doubutsu-Describer#3]
While using this in the Comfyui I am getting an error called 'PEFT is not installed' which is there on the system already. and there is one more error saying 'Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".' Could you help me to resolve this please? 

![Comfy ui](https://github.com/user-attachments/assets/220de637-0441-447e-a4a1-016698e08bf9)

**Comment by EnragedAntelope** [comment]
Hi, thanks for trying this out. I will add PEFT to the requirements. Maybe it needs a newer version? From your correct environment (venv, etc.) try:
pip install --upgrade peft

For the naistyles.csv error, that looks specific to another node: ComfyUI_NAI-mod . That is separate from this repository so you may want to ask at their GitHub.
